committees_house = [{
    congress: "114",
    chamber: "House",
    num_results: "22",
    offset: "0",
    committees: [{
        id: "HSHA",
        name: "Committee on Administration",
        url: "https://cha.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSHA.json",
        chair: "Candice S. Miller",
        chair_id: "M001150",
        chair_party: "R",
        chair_state: "MI",
        chair_uri: "https://api.propublica.org/congress/v1/members/M001150.json",
        ranking_member_id: "B001227"
    }, {
        id: "HSAG",
        name: "Committee on Agriculture",
        url: "http://agriculture.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSAG.json",
        chair: "K. Michael Conaway",
        chair_id: "C001062",
        chair_party: "R",
        chair_state: "TX",
        chair_uri: "https://api.propublica.org/congress/v1/members/C001062.json",
        ranking_member_id: "P000258"
    }, {
        id: "HSAP",
        name: "Committee on Appropriations",
        url: "http://appropriations.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSAP.json",
        chair: "Harold Rogers",
        chair_id: "R000395",
        chair_party: "R",
        chair_state: "KY",
        chair_uri: "https://api.propublica.org/congress/v1/members/R000395.json",
        ranking_member_id: "L000480"
    }, {
        id: "HSAS",
        name: "Committee on Armed Services",
        url: "https://armedservices.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSAS.json",
        chair: "William M. Thornberry",
        chair_id: "T000238",
        chair_party: "R",
        chair_state: "TX",
        chair_uri: "https://api.propublica.org/congress/v1/members/T000238.json",
        ranking_member_id: "S000510"
    }, {
        id: "HSED",
        name: "Committee on Education and the Workforce",
        url: "http://edworkforce.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSED.json",
        chair: "John Kline",
        chair_id: "K000363",
        chair_party: "R",
        chair_state: "MN",
        chair_uri: "https://api.propublica.org/congress/v1/members/K000363.json",
        ranking_member_id: "S000185"
    }, {
        id: "HSIF",
        name: "Committee on Energy and Commerce",
        url: "https://energycommerce.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSIF.json",
        chair: "Fred Upton",
        chair_id: "U000031",
        chair_party: "R",
        chair_state: "MI",
        chair_uri: "https://api.propublica.org/congress/v1/members/U000031.json",
        ranking_member_id: "P000034"
    }, {
        id: "HSBA",
        name: "Committee on Financial Services",
        url: "http://financialservices.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSBA.json",
        chair: "Jeb Hensarling",
        chair_id: "H001036",
        chair_party: "R",
        chair_state: "TX",
        chair_uri: "https://api.propublica.org/congress/v1/members/H001036.json",
        ranking_member_id: "W000187"
    }, {
        id: "HSFA",
        name: "Committee on Foreign Affairs",
        url: "http://foreignaffairs.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSFA.json",
        chair: "Ed Royce",
        chair_id: "R000487",
        chair_party: "R",
        chair_state: "CA",
        chair_uri: "https://api.propublica.org/congress/v1/members/R000487.json",
        ranking_member_id: "E000179"
    }, {
        id: "HSHM",
        name: "Committee on Homeland Security",
        url: "https://homeland.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSHM.json",
        chair: "Michael McCaul",
        chair_id: "M001157",
        chair_party: "R",
        chair_state: "TX",
        chair_uri: "https://api.propublica.org/congress/v1/members/M001157.json",
        ranking_member_id: "T000193"
    }, {
        id: "HSII",
        name: "Committee on Natural Resources",
        url: "http://naturalresources.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSII.json",
        chair: "Rob Bishop",
        chair_id: "B001250",
        chair_party: "R",
        chair_state: "UT",
        chair_uri: "https://api.propublica.org/congress/v1/members/B001250.json",
        ranking_member_id: "G000551"
    }, {
        id: "HSGO",
        name: "Committee on Oversight and Government Reform",
        url: "https://oversight.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSGO.json",
        chair: "Jason Chaffetz",
        chair_id: "C001076",
        chair_party: "R",
        chair_state: "UT",
        chair_uri: "https://api.propublica.org/congress/v1/members/C001076.json",
        ranking_member_id: "C000984"
    }, {
        id: "HSRU",
        name: "Committee on Rules",
        url: "https://rules.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSRU.json",
        chair: "Pete Sessions",
        chair_id: "S000250",
        chair_party: "R",
        chair_state: "TX",
        chair_uri: "https://api.propublica.org/congress/v1/members/S000250.json",
        ranking_member_id: "S000480"
    }, {
        id: "HSSY",
        name: "Committee on Science, Space, and Technology",
        url: "https://science.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSSY.json",
        chair: "Lamar Smith",
        chair_id: "S000583",
        chair_party: "R",
        chair_state: "TX",
        chair_uri: "https://api.propublica.org/congress/v1/members/S000583.json",
        ranking_member_id: "J000126"
    }, {
        id: "HSSM",
        name: "Committee on Small Business",
        url: "http://smallbusiness.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSSM.json",
        chair: "Steven J. Chabot",
        chair_id: "C000266",
        chair_party: "R",
        chair_state: "OH",
        chair_uri: "https://api.propublica.org/congress/v1/members/C000266.json",
        ranking_member_id: "V000081"
    }, {
        id: "HSSO",
        name: "Committee on Standards of Official Conduct",
        url: "http://ethics.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSSO.json",
        chair: "Charlie Dent",
        chair_id: "D000604",
        chair_party: "R",
        chair_state: "PA",
        chair_uri: "https://api.propublica.org/congress/v1/members/D000604.json",
        ranking_member_id: "S001156"
    }, {
        id: "HSBU",
        name: "Committee on the Budget",
        url: "http://budget.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSBU.json",
        chair: "Tom Price",
        chair_id: "P000591",
        chair_party: "R",
        chair_state: "GA",
        chair_uri: "https://api.propublica.org/congress/v1/members/P000591.json",
        ranking_member_id: "V000128"
    }, {
        id: "HSJU",
        name: "Committee on the Judiciary",
        url: "https://judiciary.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSJU.json",
        chair: "Robert W. Goodlatte",
        chair_id: "G000289",
        chair_party: "R",
        chair_state: "VA",
        chair_uri: "https://api.propublica.org/congress/v1/members/G000289.json",
        ranking_member_id: "C000714"
    }, {
        id: "HSPW",
        name: "Committee on Transportation and Infrastructure",
        url: "http://transportation.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSPW.json",
        chair: "Bill Shuster",
        chair_id: "S001154",
        chair_party: "R",
        chair_state: "PA",
        chair_uri: "https://api.propublica.org/congress/v1/members/S001154.json",
        ranking_member_id: "D000191"
    }, {
        id: "HSVR",
        name: "Committee on Veterans&#39; Affairs",
        url: "http://veterans.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSVR.json",
        chair: "Jeff Miller",
        chair_id: "M001144",
        chair_party: "R",
        chair_state: "FL",
        chair_uri: "https://api.propublica.org/congress/v1/members/M001144.json",
        ranking_member_id: "B000911"
    }, {
        id: "HSWM",
        name: "Committee on Ways and Means",
        url: "http://waysandmeans.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSWM.json",
        chair: "Kevin Brady",
        chair_id: "B000755",
        chair_party: "R",
        chair_state: "TX",
        chair_uri: "https://api.propublica.org/congress/v1/members/B000755.json",
        ranking_member_id: "L000263"
    }, {
        id: "HSIG",
        name: "Permanent Select Committee on Intelligence",
        url: "http://intelligence.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSIG.json",
        chair: "Devin Nunes",
        chair_id: "N000181",
        chair_party: "R",
        chair_state: "CA",
        chair_uri: "https://api.propublica.org/congress/v1/members/N000181.json",
        ranking_member_id: "S001150"
    }, {
        id: "HSBG",
        name: "Select Committee on Benghazi",
        url: "http://benghazi.house.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSBG.json",
        chair: "Trey Gowdy",
        chair_id: "G000566",
        chair_party: "R",
        chair_state: "SC",
        chair_uri: "https://api.propublica.org/congress/v1/members/G000566.json",
        ranking_member_id: "C000984"
    }]
}]
