committees_senate = [{
    congress: "114",
    chamber: "Senate",
    num_results: "20",
    offset: "0",
    committees: [{
        id: "SSAF",
        name: "Committee on Agriculture, Nutrition, and Forestry",
        url: "http://agriculture.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSAF.json",
        chair: "Pat Roberts",
        chair_id: "R000307",
        chair_party: "R",
        chair_state: "KS",
        chair_uri: "https://api.propublica.org/congress/v1/members/R000307.json",
        ranking_member_id: "S000770"
    }, {
        id: "SSAP",
        name: "Committee on Appropriations",
        url: "http://appropriations.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSAP.json",
        chair: "Thad Cochran",
        chair_id: "C000567",
        chair_party: "R",
        chair_state: "MS",
        chair_uri: "https://api.propublica.org/congress/v1/members/C000567.json",
        ranking_member_id: "M000702"
    }, {
        id: "SSAS",
        name: "Committee on Armed Services",
        url: "http://armed-services.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSAS.json",
        chair: "John McCain",
        chair_id: "M000303",
        chair_party: "R",
        chair_state: "AZ",
        chair_uri: "https://api.propublica.org/congress/v1/members/M000303.json",
        ranking_member_id: "R000122"
    }, {
        id: "SSBK",
        name: "Committee on Banking, Housing, and Urban Affairs",
        url: "http://banking.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSBK.json",
        chair: "Richard C. Shelby",
        chair_id: "S000320",
        chair_party: "R",
        chair_state: "AL",
        chair_uri: "https://api.propublica.org/congress/v1/members/S000320.json",
        ranking_member_id: "B000944"
    }, {
        id: "SSCM",
        name: "Committee on Commerce, Science, and Transportation",
        url: "http://commerce.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSCM.json",
        chair: "John Thune",
        chair_id: "T000250",
        chair_party: "R",
        chair_state: "SD",
        chair_uri: "https://api.propublica.org/congress/v1/members/T000250.json",
        ranking_member_id: "N000032"
    }, {
        id: "SSEG",
        name: "Committee on Energy and Natural Resources",
        url: "http://energy.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSEG.json",
        chair: "Lisa Murkowski",
        chair_id: "M001153",
        chair_party: "R",
        chair_state: "AK",
        chair_uri: "https://api.propublica.org/congress/v1/members/M001153.json",
        ranking_member_id: "C000127"
    }, {
        id: "SSEV",
        name: "Committee on Environment and Public Works",
        url: "http://www.epw.senate.gov/public/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSEV.json",
        chair: "James M. Inhofe",
        chair_id: "I000024",
        chair_party: "R",
        chair_state: "OK",
        chair_uri: "https://api.propublica.org/congress/v1/members/I000024.json",
        ranking_member_id: "B000711"
    }, {
        id: "SSFI",
        name: "Committee on Finance",
        url: "http://www.finance.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSFI.json",
        chair: "Orrin G. Hatch",
        chair_id: "H000338",
        chair_party: "R",
        chair_state: "UT",
        chair_uri: "https://api.propublica.org/congress/v1/members/H000338.json",
        ranking_member_id: "W000779"
    }, {
        id: "SSFR",
        name: "Committee on Foreign Relations",
        url: "http://www.foreign.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSFR.json",
        chair: "Bob Corker",
        chair_id: "C001071",
        chair_party: "R",
        chair_state: "TN",
        chair_uri: "https://api.propublica.org/congress/v1/members/C001071.json",
        ranking_member_id: "C000141"
    }, {
        id: "SSHR",
        name: "Committee on Health, Education, Labor, and Pensions",
        url: "http://www.help.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSHR.json",
        chair: "Lamar  Alexander",
        chair_id: "A000360",
        chair_party: "R",
        chair_state: "TN",
        chair_uri: "https://api.propublica.org/congress/v1/members/A000360.json",
        ranking_member_id: "M001111"
    }, {
        id: "SSGA",
        name: "Committee on Homeland Security and Governmental Affairs",
        url: "https://www.hsgac.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSGA.json",
        chair: "Ron Johnson",
        chair_id: "J000293",
        chair_party: "R",
        chair_state: "WI",
        chair_uri: "https://api.propublica.org/congress/v1/members/J000293.json",
        ranking_member_id: "C000174"
    }, {
        id: "SLIA",
        name: "Committee on Indian Affairs",
        url: "http://www.indian.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SLIA.json",
        chair: "John Barrasso",
        chair_id: "B001261",
        chair_party: "R",
        chair_state: "WY",
        chair_uri: "https://api.propublica.org/congress/v1/members/B001261.json",
        ranking_member_id: "B001261"
    }, {
        id: "SSRA",
        name: "Committee on Rules and Administration",
        url: "http://www.rules.senate.gov/public/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSRA.json",
        chair: "Roy  Blunt",
        chair_id: "B000575",
        chair_party: "R",
        chair_state: "MO",
        chair_uri: "https://api.propublica.org/congress/v1/members/B000575.json",
        ranking_member_id: "S000148"
    }, {
        id: "SSSB",
        name: "Committee on Small Business and Entrepreneurship",
        url: "http://www.sbc.senate.gov/public/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSSB.json",
        chair: "David Vitter",
        chair_id: "V000127",
        chair_party: "R",
        chair_state: "LA",
        chair_uri: "https://api.propublica.org/congress/v1/members/V000127.json",
        ranking_member_id: "S001181"
    }, {
        id: "SSBU",
        name: "Committee on the Budget",
        url: "http://www.budget.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSBU.json",
        chair: "Michael B. Enzi",
        chair_id: "E000285",
        chair_party: "R",
        chair_state: "WY",
        chair_uri: "https://api.propublica.org/congress/v1/members/E000285.json",
        ranking_member_id: "S000033"
    }, {
        id: "SSJU",
        name: "Committee on the Judiciary",
        url: "https://www.judiciary.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSJU.json",
        chair: "Charles E. Grassley",
        chair_id: "G000386",
        chair_party: "R",
        chair_state: "IA",
        chair_uri: "https://api.propublica.org/congress/v1/members/G000386.json",
        ranking_member_id: "L000174"
    }, {
        id: "SSVA",
        name: "Committee on Veterans&#39; Affairs",
        url: "http://www.veterans.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SSVA.json",
        chair: "Johnny Isakson",
        chair_id: "I000055",
        chair_party: "R",
        chair_state: "GA",
        chair_uri: "https://api.propublica.org/congress/v1/members/I000055.json",
        ranking_member_id: "B001277"
    }, {
        id: "SLET",
        name: "Select Committee on Ethics",
        url: "http://www.ethics.senate.gov/public/",
        democratic_rss: "",
        republican_rss: "http://www.ethics.senate.gov/public/?a=RSS.Feed",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SLET.json",
        chair: "Johnny Isakson",
        chair_id: "I000055",
        chair_party: "R",
        chair_state: "GA",
        chair_uri: "https://api.propublica.org/congress/v1/members/I000055.json",
        ranking_member_id: "I000055"
    }, {
        id: "SLIN",
        name: "Select Committee on Intelligence",
        url: "http://www.intelligence.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SLIN.json",
        chair: "Richard M. Burr",
        chair_id: "B001135",
        chair_party: "R",
        chair_state: "NC",
        chair_uri: "https://api.propublica.org/congress/v1/members/B001135.json",
        ranking_member_id: "C000286"
    }, {
        id: "SPAG",
        name: "Special Committee on Aging",
        url: "http://www.aging.senate.gov/",
        democratic_rss: "",
        republican_rss: "",
        api_uri: "https://api.propublica.org/congress/v1/114/senate/committees/SPAG.json",
        chair: "Susan Collins",
        chair_id: "C001035",
        chair_party: "R",
        chair_state: "ME",
        chair_uri: "https://api.propublica.org/congress/v1/members/C001035.json",
        ranking_member_id: "M001170"
    }]
}]
