var app = angular.module('app');

app.factory('houseCommittees', function() {

    var services = {};

    services.committees = [{
        committee: {
            id: "HSHA",
            name: "Committee on Administration",
            url: "https://cha.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSHA.json",
            chair: "Candice S. Miller",
            chair_id: "M001150",
            chair_party: "R",
            chair_state: "MI",
            chair_uri: "https://api.propublica.org/congress/v1/members/M001150.json",
            ranking_member_id: "B001227"
        },
        chair: {
            message: "@CandiceMiller ",
            id: "M001150",
            thomas_id: "1731",
            api_uri: "https://api.propublica.org/congress/v1/members/M001150.json",
            first_name: "Candice",
            middle_name: "S.",
            last_name: "Miller",
            party: "R",
            twitter_account: "CandiceMiller",
            facebook_account: "CongresswomanCandiceMiller",
            facebook_id: "210401648605",
            google_entity_id: "/m/03tl30",
            url: "http://candicemiller.house.gov",
            rss_url: "http://candicemiller.house.gov/rss.xml",
            domain: "candicemiller.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "14",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "95",
            total_present: "0",
            state: "MI",
            district: "10",
            missed_votes_pct: 7.17,
            votes_with_party_pct: "94.63"
        },
        ranking_member: {
            message: "@RepBrady ",
            id: "B001227",
            thomas_id: "1469",
            api_uri: "https://api.propublica.org/congress/v1/members/B001227.json",
            first_name: "Robert",
            middle_name: "A.",
            last_name: "Brady",
            party: "D",
            twitter_account: "RepBrady",
            facebook_account: "RepRobertBrady",
            facebook_id: "118845109487",
            google_entity_id: "/m/03tq5z",
            url: "http://brady.house.gov",
            rss_url: "http://brady.house.gov/rss.xml",
            domain: "www.brady.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "20",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "71",
            total_present: "0",
            state: "PA",
            district: "1",
            missed_votes_pct: 5.36,
            votes_with_party_pct: "95.93"
        }
    }, {
        committee: {
            id: "HSAG",
            name: "Committee on Agriculture",
            url: "http://agriculture.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSAG.json",
            chair: "K. Michael Conaway",
            chair_id: "C001062",
            chair_party: "R",
            chair_state: "TX",
            chair_uri: "https://api.propublica.org/congress/v1/members/C001062.json",
            ranking_member_id: "P000258"
        },
        chair: {
            message: "@ConawayTX11 ",
            id: "C001062",
            thomas_id: "1805",
            api_uri: "https://api.propublica.org/congress/v1/members/C001062.json",
            first_name: "K.",
            middle_name: "Michael",
            last_name: "Conaway",
            party: "R",
            twitter_account: "ConawayTX11",
            facebook_account: "mike.conaway",
            facebook_id: "203482063021985",
            google_entity_id: "/m/04cmt7",
            url: "http://conaway.house.gov",
            rss_url: "",
            domain: "conaway.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "12",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "0",
            total_present: "0",
            state: "TX",
            district: "11",
            missed_votes_pct: 0.00,
            votes_with_party_pct: "96.23"
        },
        ranking_member: {
            message:  " ",
            id: "P000258",
            thomas_id: "910",
            api_uri: "https://api.propublica.org/congress/v1/members/P000258.json",
            first_name: "Collin",
            middle_name: "C.",
            last_name: "Peterson",
            party: "D",
            twitter_account: "",
            facebook_account: "",
            facebook_id: "",
            google_entity_id: "/m/02h2my",
            url: "http://collinpeterson.house.gov",
            rss_url: "http://collinpeterson.house.gov/rss.xml",
            domain: "collinpeterson.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "26",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "16",
            total_present: "0",
            state: "MN",
            district: "7",
            missed_votes_pct: 1.21,
            votes_with_party_pct: "64.40"
        }
    }, {
        committee: {
            id: "HSAP",
            name: "Committee on Appropriations",
            url: "http://appropriations.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSAP.json",
            chair: "Harold Rogers",
            chair_id: "R000395",
            chair_party: "R",
            chair_state: "KY",
            chair_uri: "https://api.propublica.org/congress/v1/members/R000395.json",
            ranking_member_id: "L000480"
        },
        chair: {
            message: "@RepHalRogers ",
            id: "R000395",
            thomas_id: "977",
            api_uri: "https://api.propublica.org/congress/v1/members/R000395.json",
            first_name: "Harold",
            middle_name: null,
            last_name: "Rogers",
            party: "R",
            twitter_account: "RepHalRogers",
            facebook_account: "CongressmanHalRogers",
            facebook_id: "6722039085",
            google_entity_id: "/m/025jnx",
            url: "http://halrogers.house.gov",
            rss_url: "http://halrogers.house.gov/news/rss.aspx",
            domain: "halrogers.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "36",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "15",
            total_present: "0",
            state: "KY",
            district: "5",
            missed_votes_pct: 1.13,
            votes_with_party_pct: "94.12"
        },
        ranking_member: {
            message: "@NitaLowey ",
            id: "L000480",
            thomas_id: "709",
            api_uri: "https://api.propublica.org/congress/v1/members/L000480.json",
            first_name: "Nita",
            middle_name: "M.",
            last_name: "Lowey",
            party: "D",
            twitter_account: "NitaLowey",
            facebook_account: "RepLowey",
            facebook_id: "158290607551599",
            google_entity_id: "/m/03tv8l",
            url: "http://lowey.house.gov",
            rss_url: "",
            domain: "lowey.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "28",
            next_election: "2016",
            total_votes: "1320",
            missed_votes: "13",
            total_present: "0",
            state: "NY",
            district: "17",
            missed_votes_pct: 0.98,
            votes_with_party_pct: "96.40"
        }
    }, {
        committee: {
            id: "HSAS",
            name: "Committee on Armed Services",
            url: "https://armedservices.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSAS.json",
            chair: "William M. Thornberry",
            chair_id: "T000238",
            chair_party: "R",
            chair_state: "TX",
            chair_uri: "https://api.propublica.org/congress/v1/members/T000238.json",
            ranking_member_id: "S000510"
        },
        chair: {
            message: "@MacTXPress ",
            id: "T000238",
            thomas_id: "1155",
            api_uri: "https://api.propublica.org/congress/v1/members/T000238.json",
            first_name: "William",
            middle_name: "M.",
            last_name: "Thornberry",
            party: "R",
            twitter_account: "MacTXPress",
            facebook_account: "repmacthornberry",
            facebook_id: "7760165627",
            google_entity_id: "/m/03dnvd",
            url: "http://thornberry.house.gov",
            rss_url: "",
            domain: "thornberry.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "22",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "12",
            total_present: "0",
            state: "TX",
            district: "13",
            missed_votes_pct: 0.91,
            votes_with_party_pct: "96.27"
        },
        ranking_member: {
            message: "@RepAdamSmith ",
            id: "S000510",
            thomas_id: "1528",
            api_uri: "https://api.propublica.org/congress/v1/members/S000510.json",
            first_name: "Adam",
            middle_name: null,
            last_name: "Smith",
            party: "D",
            twitter_account: "RepAdamSmith",
            facebook_account: "RepAdamSmith",
            facebook_id: "288586617834523",
            google_entity_id: "/m/0tfc",
            url: "https://adamsmith.house.gov",
            rss_url: "https://adamsmith.house.gov/rss.xml",
            domain: "adamsmith.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "20",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "267",
            total_present: "0",
            state: "WA",
            district: "9",
            missed_votes_pct: 20.15,
            votes_with_party_pct: "95.65"
        }
    }, {
        committee: {
            id: "HSED",
            name: "Committee on Education and the Workforce",
            url: "http://edworkforce.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSED.json",
            chair: "John Kline",
            chair_id: "K000363",
            chair_party: "R",
            chair_state: "MN",
            chair_uri: "https://api.propublica.org/congress/v1/members/K000363.json",
            ranking_member_id: "S000185"
        },
        chair: {
            message: "@RepJohnKline ",
            id: "K000363",
            thomas_id: "1733",
            api_uri: "https://api.propublica.org/congress/v1/members/K000363.json",
            first_name: "John",
            middle_name: null,
            last_name: "Kline",
            party: "R",
            twitter_account: "RepJohnKline",
            facebook_account: "repjohnkline",
            facebook_id: "770135879667732",
            google_entity_id: "/m/02h1yr",
            url: "http://kline.house.gov",
            rss_url: "http://kline.house.gov/news/rss.aspx",
            domain: "kline.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "14",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "15",
            total_present: "0",
            state: "MN",
            district: "2",
            missed_votes_pct: 1.13,
            votes_with_party_pct: "95.95"
        },
        ranking_member: {
            message: "@RepBobbyScott ",
            id: "S000185",
            thomas_id: "1037",
            api_uri: "https://api.propublica.org/congress/v1/members/S000185.json",
            first_name: "Robert",
            middle_name: "C.",
            last_name: "Scott",
            party: "D",
            twitter_account: "RepBobbyScott",
            facebook_account: "CongressmanBobbyScott",
            facebook_id: "123839200978190",
            google_entity_id: "/m/03twgl",
            url: "http://bobbyscott.house.gov",
            rss_url: "http://bobbyscott.house.gov/rss.xml",
            domain: "www.bobbyscott.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "24",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "11",
            total_present: "0",
            state: "VA",
            district: "3",
            missed_votes_pct: 0.83,
            votes_with_party_pct: "96.88"
        }
    }, {
        committee: {
            id: "HSIF",
            name: "Committee on Energy and Commerce",
            url: "https://energycommerce.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSIF.json",
            chair: "Fred Upton",
            chair_id: "U000031",
            chair_party: "R",
            chair_state: "MI",
            chair_uri: "https://api.propublica.org/congress/v1/members/U000031.json",
            ranking_member_id: "P000034"
        },
        chair: {
            message: "@RepFredUpton ",
            id: "U000031",
            thomas_id: "1177",
            api_uri: "https://api.propublica.org/congress/v1/members/U000031.json",
            first_name: "Fred",
            middle_name: null,
            last_name: "Upton",
            party: "R",
            twitter_account: "RepFredUpton",
            facebook_account: "RepFredUpton",
            facebook_id: "212027388827797",
            google_entity_id: "/m/02d4c3",
            url: "http://upton.house.gov",
            rss_url: "http://upton.house.gov/news/rss.aspx",
            domain: "upton.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "30",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "0",
            total_present: "0",
            state: "MI",
            district: "6",
            missed_votes_pct: 0.00,
            votes_with_party_pct: "92.00"
        },
        ranking_member: {
            message: "@FrankPallone ",
            id: "P000034",
            thomas_id: "887",
            api_uri: "https://api.propublica.org/congress/v1/members/P000034.json",
            first_name: "Frank",
            middle_name: null,
            last_name: "Pallone",
            party: "D",
            twitter_account: "FrankPallone",
            facebook_account: "repfrankpallone",
            facebook_id: "6517277731",
            google_entity_id: "/m/0g6t5w",
            url: "https://pallone.house.gov",
            rss_url: "http://pallone.house.gov/rss.xml",
            domain: "pallone.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "30",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "25",
            total_present: "0",
            state: "NJ",
            district: "6",
            missed_votes_pct: 1.89,
            votes_with_party_pct: "95.38"
        }
    }, {
        committee: {
            id: "HSBA",
            name: "Committee on Financial Services",
            url: "http://financialservices.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSBA.json",
            chair: "Jeb Hensarling",
            chair_id: "H001036",
            chair_party: "R",
            chair_state: "TX",
            chair_uri: "https://api.propublica.org/congress/v1/members/H001036.json",
            ranking_member_id: "W000187"
        },
        chair: {
            message: "@RepHensarling ",
            id: "H001036",
            thomas_id: "1749",
            api_uri: "https://api.propublica.org/congress/v1/members/H001036.json",
            first_name: "Jeb",
            middle_name: null,
            last_name: "Hensarling",
            party: "R",
            twitter_account: "RepHensarling",
            facebook_account: "RepHensarling",
            facebook_id: "7875604788",
            google_entity_id: "/m/0h23n6",
            url: "http://hensarling.house.gov",
            rss_url: "http://hensarling.house.gov/rss.xml",
            domain: "hensarling.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "14",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "15",
            total_present: "0",
            state: "TX",
            district: "5",
            missed_votes_pct: 1.13,
            votes_with_party_pct: "96.72"
        },
        ranking_member: {
            message: "@MaxineWaters ",
            id: "W000187",
            thomas_id: "1205",
            api_uri: "https://api.propublica.org/congress/v1/members/W000187.json",
            first_name: "Maxine",
            middle_name: null,
            last_name: "Waters",
            party: "D",
            twitter_account: "MaxineWaters",
            facebook_account: "MaxineWaters",
            facebook_id: "117483585008",
            google_entity_id: "/m/024tyk",
            url: "http://waters.house.gov",
            rss_url: "",
            domain: "waters.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "26",
            next_election: "2016",
            total_votes: "1311",
            missed_votes: "100",
            total_present: "0",
            state: "CA",
            district: "43",
            missed_votes_pct: 7.63,
            votes_with_party_pct: "95.54"
        }
    }, {
        committee: {
            id: "HSFA",
            name: "Committee on Foreign Affairs",
            url: "http://foreignaffairs.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSFA.json",
            chair: "Ed Royce",
            chair_id: "R000487",
            chair_party: "R",
            chair_state: "CA",
            chair_uri: "https://api.propublica.org/congress/v1/members/R000487.json",
            ranking_member_id: "E000179"
        },
        chair: {
            message: "@RepEdRoyce ",
            id: "R000487",
            thomas_id: "998",
            api_uri: "https://api.propublica.org/congress/v1/members/R000487.json",
            first_name: "Ed",
            middle_name: null,
            last_name: "Royce",
            party: "R",
            twitter_account: "RepEdRoyce",
            facebook_account: "EdRoyce",
            facebook_id: "6460640558",
            google_entity_id: "/m/024xcy",
            url: "http://royce.house.gov",
            rss_url: "http://royce.house.gov/news/rss.aspx",
            domain: "www.royce.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "24",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "13",
            total_present: "0",
            state: "CA",
            district: "39",
            missed_votes_pct: 0.98,
            votes_with_party_pct: "94.66"
        },
        ranking_member: {
            message: "@RepEliotEngel ",
            id: "E000179",
            thomas_id: "344",
            api_uri: "https://api.propublica.org/congress/v1/members/E000179.json",
            first_name: "Eliot",
            middle_name: "L.",
            last_name: "Engel",
            party: "D",
            twitter_account: "RepEliotEngel",
            facebook_account: "RepEliotLEngel",
            facebook_id: "103355984852",
            google_entity_id: "/m/03tt1r",
            url: "http://engel.house.gov",
            rss_url: "https://engel.house.gov/rss/latest-news1.xml",
            domain: "engel.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "28",
            next_election: "2016",
            total_votes: "1320",
            missed_votes: "94",
            total_present: "0",
            state: "NY",
            district: "16",
            missed_votes_pct: 7.12,
            votes_with_party_pct: "95.92"
        }
    }, {
        committee: {
            id: "HSHM",
            name: "Committee on Homeland Security",
            url: "https://homeland.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSHM.json",
            chair: "Michael McCaul",
            chair_id: "M001157",
            chair_party: "R",
            chair_state: "TX",
            chair_uri: "https://api.propublica.org/congress/v1/members/M001157.json",
            ranking_member_id: "T000193"
        },
        chair: {
            message: "@RepMcCaul ",
            id: "M001157",
            thomas_id: "1804",
            api_uri: "https://api.propublica.org/congress/v1/members/M001157.json",
            first_name: "Michael",
            middle_name: null,
            last_name: "McCaul",
            party: "R",
            twitter_account: "RepMcCaul",
            facebook_account: "michaeltmccaul",
            facebook_id: "6355254859",
            google_entity_id: "/m/0492cz",
            url: "http://mccaul.house.gov",
            rss_url: "",
            domain: "mccaul.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "12",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "28",
            total_present: "0",
            state: "TX",
            district: "10",
            missed_votes_pct: 2.11,
            votes_with_party_pct: "96.53"
        },
        ranking_member: {
            message: "@BennieGThompson ",
            id: "T000193",
            thomas_id: "1151",
            api_uri: "https://api.propublica.org/congress/v1/members/T000193.json",
            first_name: "Bennie",
            middle_name: null,
            last_name: "Thompson",
            party: "D",
            twitter_account: "BennieGThompson",
            facebook_account: "7259193379",
            facebook_id: "7259193379",
            google_entity_id: "/m/033tc5",
            url: "http://benniethompson.house.gov",
            rss_url: "http://benniethompson.house.gov/index.php?format=feed&amp;type=rss",
            domain: "benniethompson.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "24",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "52",
            total_present: "0",
            state: "MS",
            district: "2",
            missed_votes_pct: 3.92,
            votes_with_party_pct: "94.89"
        }
    }, {
        committee: {
            id: "HSII",
            name: "Committee on Natural Resources",
            url: "http://naturalresources.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSII.json",
            chair: "Rob Bishop",
            chair_id: "B001250",
            chair_party: "R",
            chair_state: "UT",
            chair_uri: "https://api.propublica.org/congress/v1/members/B001250.json",
            ranking_member_id: "G000551"
        },
        chair: {
            message: "@RepRobBishop ",
            id: "B001250",
            thomas_id: "1753",
            api_uri: "https://api.propublica.org/congress/v1/members/B001250.json",
            first_name: "Rob",
            middle_name: null,
            last_name: "Bishop",
            party: "R",
            twitter_account: "RepRobBishop",
            facebook_account: "RepRobBishop",
            facebook_id: "",
            google_entity_id: "/m/02tn41",
            url: "http://robbishop.house.gov",
            rss_url: "http://robbishop.house.gov/news/rss.aspx",
            domain: "robbishop.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "14",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "66",
            total_present: "0",
            state: "UT",
            district: "1",
            missed_votes_pct: 4.98,
            votes_with_party_pct: "95.55"
        },
        ranking_member: {
            message: "@RepraulGrijalva ",
            id: "G000551",
            thomas_id: "1708",
            api_uri: "https://api.propublica.org/congress/v1/members/G000551.json",
            first_name: "Raúl",
            middle_name: "M.",
            last_name: "Grijalva",
            party: "D",
            twitter_account: "RepraulGrijalva",
            facebook_account: "Rep.Grijalva",
            facebook_id: "73539896233",
            google_entity_id: "/m/024s1z",
            url: "http://grijalva.house.gov",
            rss_url: "https://grijalva.house.gov/common/rss/?rss=13",
            domain: "grijalva.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "14",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "135",
            total_present: "0",
            state: "AZ",
            district: "3",
            missed_votes_pct: 10.19,
            votes_with_party_pct: "94.62"
        }
    }, {
        committee: {
            id: "HSGO",
            name: "Committee on Oversight and Government Reform",
            url: "https://oversight.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSGO.json",
            chair: "Jason Chaffetz",
            chair_id: "C001076",
            chair_party: "R",
            chair_state: "UT",
            chair_uri: "https://api.propublica.org/congress/v1/members/C001076.json",
            ranking_member_id: "C000984"
        },
        chair: {
            message: "@JasonInTheHouse ",
            id: "C001076",
            thomas_id: "1956",
            api_uri: "https://api.propublica.org/congress/v1/members/C001076.json",
            first_name: "Jason",
            middle_name: null,
            last_name: "Chaffetz",
            party: "R",
            twitter_account: "JasonInTheHouse",
            facebook_account: "CongressmanJasonChaffetz",
            facebook_id: "390419731073316",
            google_entity_id: "/m/047blr4",
            url: "http://chaffetz.house.gov",
            rss_url: "",
            domain: "chaffetz.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "8",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "52",
            total_present: "0",
            state: "UT",
            district: "3",
            missed_votes_pct: 3.92,
            votes_with_party_pct: "94.19"
        },
        ranking_member: {
            message: "@RepCummings ",
            id: "C000984",
            thomas_id: "256",
            api_uri: "https://api.propublica.org/congress/v1/members/C000984.json",
            first_name: "Elijah",
            middle_name: "E.",
            last_name: "Cummings",
            party: "D",
            twitter_account: "RepCummings",
            facebook_account: "elijahcummings",
            facebook_id: "291368465380",
            google_entity_id: "/m/025k9h",
            url: "http://cummings.house.gov",
            rss_url: "https://cummings.house.gov/rss.xml",
            domain: "cummings.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "22",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "39",
            total_present: "0",
            state: "MD",
            district: "7",
            missed_votes_pct: 2.94,
            votes_with_party_pct: "97.05"
        }
    }, {
        committee: {
            id: "HSRU",
            name: "Committee on Rules",
            url: "https://rules.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSRU.json",
            chair: "Pete Sessions",
            chair_id: "S000250",
            chair_party: "R",
            chair_state: "TX",
            chair_uri: "https://api.propublica.org/congress/v1/members/S000250.json",
            ranking_member_id: "S000480"
        },
        chair: {
            message: "@PeteSessions ",
            id: "S000250",
            thomas_id: "1525",
            api_uri: "https://api.propublica.org/congress/v1/members/S000250.json",
            first_name: "Pete",
            middle_name: null,
            last_name: "Sessions",
            party: "R",
            twitter_account: "PeteSessions",
            facebook_account: "petesessions",
            facebook_id: "367963843082",
            google_entity_id: "/m/03v39l",
            url: "https://sessions.house.gov",
            rss_url: "https://sessions.house.gov/rss.xml",
            domain: "sessions.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "20",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "24",
            total_present: "0",
            state: "TX",
            district: "32",
            missed_votes_pct: 1.81,
            votes_with_party_pct: "97.23"
        },
        ranking_member: {
            message: "@LouiseSlaughter ",
            id: "S000480",
            thomas_id: "1069",
            api_uri: "https://api.propublica.org/congress/v1/members/S000480.json",
            first_name: "Louise",
            middle_name: "M.",
            last_name: "Slaughter",
            party: "D",
            twitter_account: "LouiseSlaughter",
            facebook_account: "RepLouiseSlaughter",
            facebook_id: "82424647700",
            google_entity_id: "/m/03tvt9",
            url: "https://louise.house.gov",
            rss_url: "",
            domain: "www.louise.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "30",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "40",
            total_present: "1",
            state: "NY",
            district: "25",
            missed_votes_pct: 3.02,
            votes_with_party_pct: "95.56"
        }
    }, {
        committee: {
            id: "HSSY",
            name: "Committee on Science, Space, and Technology",
            url: "https://science.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSSY.json",
            chair: "Lamar Smith",
            chair_id: "S000583",
            chair_party: "R",
            chair_state: "TX",
            chair_uri: "https://api.propublica.org/congress/v1/members/S000583.json",
            ranking_member_id: "J000126"
        },
        chair: {
            message: "@LamarSmithTX21 ",
            id: "S000583",
            thomas_id: "1075",
            api_uri: "https://api.propublica.org/congress/v1/members/S000583.json",
            first_name: "Lamar",
            middle_name: null,
            last_name: "Smith",
            party: "R",
            twitter_account: "LamarSmithTX21",
            facebook_account: "LamarSmithTX21",
            facebook_id: "107736785195",
            google_entity_id: "/m/03twnt",
            url: "http://lamarsmith.house.gov",
            rss_url: "http://lamarsmith.house.gov/rss.xml",
            domain: "lamarsmith.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "30",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "26",
            total_present: "0",
            state: "TX",
            district: "21",
            missed_votes_pct: 1.96,
            votes_with_party_pct: "96.77"
        },
        ranking_member: {
            message: "@RepEBJ ",
            id: "J000126",
            thomas_id: "599",
            api_uri: "https://api.propublica.org/congress/v1/members/J000126.json",
            first_name: "Eddie",
            middle_name: "Bernice",
            last_name: "Johnson",
            party: "D",
            twitter_account: "RepEBJ",
            facebook_account: "CongresswomanEBJtx30",
            facebook_id: "84096022067",
            google_entity_id: "/m/03tn1w",
            url: "http://ebjohnson.house.gov",
            rss_url: "http://ebjohnson.house.gov/rss.xml",
            domain: "ebjohnson.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "24",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "99",
            total_present: "2",
            state: "TX",
            district: "30",
            missed_votes_pct: 7.47,
            votes_with_party_pct: "93.96"
        }
    }, {
        committee: {
            id: "HSSM",
            name: "Committee on Small Business",
            url: "http://smallbusiness.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSSM.json",
            chair: "Steven J. Chabot",
            chair_id: "C000266",
            chair_party: "R",
            chair_state: "OH",
            chair_uri: "https://api.propublica.org/congress/v1/members/C000266.json",
            ranking_member_id: "V000081"
        },
        chair: {
            message: "@RepSteveChabot ",
            id: "C000266",
            thomas_id: "186",
            api_uri: "https://api.propublica.org/congress/v1/members/C000266.json",
            first_name: "Steven",
            middle_name: "J.",
            last_name: "Chabot",
            party: "R",
            twitter_account: "RepSteveChabot",
            facebook_account: "RepSteveChabot",
            facebook_id: "204705339555378",
            google_entity_id: "/m/0343vk",
            url: "http://chabot.house.gov",
            rss_url: "",
            domain: "chabot.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "6",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "1",
            total_present: "0",
            state: "OH",
            district: "1",
            missed_votes_pct: 0.08,
            votes_with_party_pct: "97.05"
        },
        ranking_member: {
            message: "@NydiaVelazquez ",
            id: "V000081",
            thomas_id: "1184",
            api_uri: "https://api.propublica.org/congress/v1/members/V000081.json",
            first_name: "Nydia",
            middle_name: "M.",
            last_name: "Velázquez",
            party: "D",
            twitter_account: "NydiaVelazquez",
            facebook_account: "8037068318",
            facebook_id: "8037068318",
            google_entity_id: "/m/03sjbt",
            url: "http://velazquez.house.gov",
            rss_url: "",
            domain: "velazquez.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "24",
            next_election: "2016",
            total_votes: "1320",
            missed_votes: "22",
            total_present: "0",
            state: "NY",
            district: "7",
            missed_votes_pct: 1.67,
            votes_with_party_pct: "95.99"
        }
    }, {
        committee: {
            id: "HSSO",
            name: "Committee on Standards of Official Conduct",
            url: "http://ethics.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSSO.json",
            chair: "Charlie Dent",
            chair_id: "D000604",
            chair_party: "R",
            chair_state: "PA",
            chair_uri: "https://api.propublica.org/congress/v1/members/D000604.json",
            ranking_member_id: "S001156"
        },
        chair: {
            message:  " ",
            id: "D000604",
            thomas_id: "1799",
            api_uri: "https://api.propublica.org/congress/v1/members/D000604.json",
            first_name: "Charlie",
            middle_name: null,
            last_name: "Dent",
            party: "R",
            twitter_account: "",
            facebook_account: "CongressmanDent",
            facebook_id: "69862092533",
            google_entity_id: "/m/04fcm3",
            url: "https://dent.house.gov",
            rss_url: "http://dent.house.gov/?a=RSS.Feed",
            domain: "dent.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "12",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "2",
            total_present: "0",
            state: "PA",
            district: "15",
            missed_votes_pct: 0.15,
            votes_with_party_pct: "88.44"
        },
        ranking_member: {
            message: "@RepLindaSanchez ",
            id: "S001156",
            thomas_id: "1757",
            api_uri: "https://api.propublica.org/congress/v1/members/S001156.json",
            first_name: "Linda",
            middle_name: "T.",
            last_name: "Sánchez",
            party: "D",
            twitter_account: "RepLindaSanchez",
            facebook_account: "CongresswomanLindaSanchez",
            facebook_id: "110685735673141",
            google_entity_id: "/m/024xc7",
            url: "https://lindasanchez.house.gov",
            rss_url: "https://lindasanchez.house.gov/rss.xml",
            domain: "lindasanchez.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "14",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "36",
            total_present: "0",
            state: "CA",
            district: "38",
            missed_votes_pct: 2.72,
            votes_with_party_pct: "96.59"
        }
    }, {
        committee: {
            id: "HSBU",
            name: "Committee on the Budget",
            url: "http://budget.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSBU.json",
            chair: "Tom Price",
            chair_id: "P000591",
            chair_party: "R",
            chair_state: "GA",
            chair_uri: "https://api.propublica.org/congress/v1/members/P000591.json",
            ranking_member_id: "V000128"
        },
        chair: {
            message: "@RepTomPrice ",
            id: "P000591",
            thomas_id: "1778",
            api_uri: "https://api.propublica.org/congress/v1/members/P000591.json",
            first_name: "Tom",
            middle_name: null,
            last_name: "Price",
            party: "R",
            twitter_account: "RepTomPrice",
            facebook_account: "reptomprice",
            facebook_id: "172032960420",
            google_entity_id: "/m/04z48c",
            url: "https://tomprice.house.gov",
            rss_url: "http://tomprice.house.gov/rss.xml",
            domain: "tomprice.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "12",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "50",
            total_present: "0",
            state: "GA",
            district: "6",
            missed_votes_pct: 3.77,
            votes_with_party_pct: "94.20"
        },
        ranking_member: {
            message: "@ChrisVanHollen ",
            id: "V000128",
            thomas_id: "1729",
            api_uri: "https://api.propublica.org/congress/v1/members/V000128.json",
            first_name: "Chris",
            middle_name: null,
            last_name: "Van Hollen",
            party: "D",
            twitter_account: "ChrisVanHollen",
            facebook_account: "chrisvanhollen",
            facebook_id: "109304033877",
            google_entity_id: "/m/025kb5",
            url: "",
            rss_url: "https://vanhollen.house.gov/rss.xml",
            domain: "vanhollen.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "14",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "40",
            total_present: "0",
            state: "MD",
            district: "8",
            missed_votes_pct: 3.02,
            votes_with_party_pct: "97.28"
        }
    }, {
        committee: {
            id: "HSJU",
            name: "Committee on the Judiciary",
            url: "https://judiciary.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSJU.json",
            chair: "Robert W. Goodlatte",
            chair_id: "G000289",
            chair_party: "R",
            chair_state: "VA",
            chair_uri: "https://api.propublica.org/congress/v1/members/G000289.json",
            ranking_member_id: "C000714"
        },
        chair: {
            message: "@RepGoodlatte ",
            id: "G000289",
            thomas_id: "446",
            api_uri: "https://api.propublica.org/congress/v1/members/G000289.json",
            first_name: "Robert",
            middle_name: "W.",
            last_name: "Goodlatte",
            party: "R",
            twitter_account: "RepGoodlatte",
            facebook_account: "BobGoodlatte",
            facebook_id: "6459789414",
            google_entity_id: "/m/0284s7",
            url: "http://goodlatte.house.gov",
            rss_url: "",
            domain: "goodlatte.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "24",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "18",
            total_present: "0",
            state: "VA",
            district: "6",
            missed_votes_pct: 1.36,
            votes_with_party_pct: "96.48"
        },
        ranking_member: {
            message: "@RepJohnConyers ",
            id: "C000714",
            thomas_id: "229",
            api_uri: "https://api.propublica.org/congress/v1/members/C000714.json",
            first_name: "John",
            middle_name: null,
            last_name: "Conyers Jr.",
            party: "D",
            twitter_account: "RepJohnConyers",
            facebook_account: "CongressmanConyers",
            facebook_id: "206947066849",
            google_entity_id: "/m/02hy5d",
            url: "https://conyers.house.gov",
            rss_url: "https://conyers.house.gov/rss.xml",
            domain: "conyers.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "52",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "72",
            total_present: "0",
            state: "MI",
            district: "13",
            missed_votes_pct: 5.43,
            votes_with_party_pct: "95.37"
        }
    }, {
        committee: {
            id: "HSPW",
            name: "Committee on Transportation and Infrastructure",
            url: "http://transportation.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSPW.json",
            chair: "Bill Shuster",
            chair_id: "S001154",
            chair_party: "R",
            chair_state: "PA",
            chair_uri: "https://api.propublica.org/congress/v1/members/S001154.json",
            ranking_member_id: "D000191"
        },
        chair: {
            message: "@RepBillShuster ",
            id: "S001154",
            thomas_id: "1681",
            api_uri: "https://api.propublica.org/congress/v1/members/S001154.json",
            first_name: "Bill",
            middle_name: null,
            last_name: "Shuster",
            party: "R",
            twitter_account: "RepBillShuster",
            facebook_account: "Rep.Shuster",
            facebook_id: "54386677806",
            google_entity_id: "/m/03tm89",
            url: "http://shuster.house.gov",
            rss_url: "https://shuster.house.gov/common/rss/index.cfm?rss=49",
            domain: "shuster.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "16",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "13",
            total_present: "0",
            state: "PA",
            district: "9",
            missed_votes_pct: 0.98,
            votes_with_party_pct: "94.13"
        },
        ranking_member: {
            message: "@RepPeterDeFazio ",
            id: "D000191",
            thomas_id: "279",
            api_uri: "https://api.propublica.org/congress/v1/members/D000191.json",
            first_name: "Peter",
            middle_name: "A.",
            last_name: "DeFazio",
            party: "D",
            twitter_account: "RepPeterDeFazio",
            facebook_account: "RepPeterDeFazio",
            facebook_id: "94324364811",
            google_entity_id: "/m/033ttx",
            url: "http://defazio.house.gov",
            rss_url: "http://defazio.house.gov/rss.xml",
            domain: "www.defazio.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "30",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "107",
            total_present: "2",
            state: "OR",
            district: "4",
            missed_votes_pct: 8.08,
            votes_with_party_pct: "91.22"
        }
    }, {
        committee: {
            id: "HSVR",
            name: "Committee on Veterans&#39; Affairs",
            url: "http://veterans.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSVR.json",
            chair: "Jeff Miller",
            chair_id: "M001144",
            chair_party: "R",
            chair_state: "FL",
            chair_uri: "https://api.propublica.org/congress/v1/members/M001144.json",
            ranking_member_id: "B000911"
        },
        chair: {
            message:  " ",
            id: "M001144",
            thomas_id: "1685",
            api_uri: "https://api.propublica.org/congress/v1/members/M001144.json",
            first_name: "Jeff",
            middle_name: null,
            last_name: "Miller",
            party: "R",
            twitter_account: "",
            facebook_account: "RepJeffMiller",
            facebook_id: "66367876671",
            google_entity_id: "/m/0251vm",
            url: "http://jeffmiller.house.gov",
            rss_url: "http://jeffmiller.house.gov/news/rss.aspx",
            domain: "jeffmiller.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "16",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "42",
            total_present: "0",
            state: "FL",
            district: "1",
            missed_votes_pct: 3.17,
            votes_with_party_pct: "95.09"
        },
        ranking_member: {
            message: "@RepCorrineBrown ",
            id: "B000911",
            thomas_id: "132",
            api_uri: "https://api.propublica.org/congress/v1/members/B000911.json",
            first_name: "Corrine",
            middle_name: null,
            last_name: "Brown",
            party: "D",
            twitter_account: "RepCorrineBrown",
            facebook_account: "congresswomanbrown",
            facebook_id: "179120958813519",
            google_entity_id: "/m/0251xd",
            url: "https://corrinebrown.house.gov",
            rss_url: "https://corrinebrown.house.gov/rss.xml",
            domain: "corrinebrown.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "24",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "187",
            total_present: "0",
            state: "FL",
            district: "5",
            missed_votes_pct: 14.11,
            votes_with_party_pct: "94.82"
        }
    }, {
        committee: {
            id: "HSWM",
            name: "Committee on Ways and Means",
            url: "http://waysandmeans.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSWM.json",
            chair: "Kevin Brady",
            chair_id: "B000755",
            chair_party: "R",
            chair_state: "TX",
            chair_uri: "https://api.propublica.org/congress/v1/members/B000755.json",
            ranking_member_id: "L000263"
        },
        chair: {
            message: "@RepKevinBrady ",
            id: "B000755",
            thomas_id: "1468",
            api_uri: "https://api.propublica.org/congress/v1/members/B000755.json",
            first_name: "Kevin",
            middle_name: null,
            last_name: "Brady",
            party: "R",
            twitter_account: "RepKevinBrady",
            facebook_account: "kevinbrady",
            facebook_id: "9307301412",
            google_entity_id: "/m/03tq00",
            url: "http://kevinbrady.house.gov",
            rss_url: "",
            domain: "kevinbrady.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "20",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "61",
            total_present: "0",
            state: "TX",
            district: "8",
            missed_votes_pct: 4.60,
            votes_with_party_pct: "97.23"
        },
        ranking_member: {
            message: "@RepSandyLevin ",
            id: "L000263",
            thomas_id: "683",
            api_uri: "https://api.propublica.org/congress/v1/members/L000263.json",
            first_name: "Sander",
            middle_name: "M.",
            last_name: "Levin",
            party: "D",
            twitter_account: "RepSandyLevin",
            facebook_account: "RepSandyLevin",
            facebook_id: "223726364320243",
            google_entity_id: "/m/02n8p2",
            url: "http://levin.house.gov",
            rss_url: "http://levin.house.gov/press-rss.xml",
            domain: "levin.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "34",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "21",
            total_present: "0",
            state: "MI",
            district: "9",
            missed_votes_pct: 1.58,
            votes_with_party_pct: "96.93"
        }
    }, {
        committee: {
            id: "HSIG",
            name: "Permanent Select Committee on Intelligence",
            url: "http://intelligence.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSIG.json",
            chair: "Devin Nunes",
            chair_id: "N000181",
            chair_party: "R",
            chair_state: "CA",
            chair_uri: "https://api.propublica.org/congress/v1/members/N000181.json",
            ranking_member_id: "S001150"
        },
        chair: {
            message: "@Rep_DevinNunes ",
            id: "N000181",
            thomas_id: "1710",
            api_uri: "https://api.propublica.org/congress/v1/members/N000181.json",
            first_name: "Devin",
            middle_name: null,
            last_name: "Nunes",
            party: "R",
            twitter_account: "Rep_DevinNunes",
            facebook_account: "",
            facebook_id: "",
            google_entity_id: "/m/024tds",
            url: "http://nunes.house.gov",
            rss_url: "http://nunes.house.gov/news/rss.aspx",
            domain: "nunes.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "14",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "4",
            total_present: "0",
            state: "CA",
            district: "22",
            missed_votes_pct: 0.30,
            votes_with_party_pct: "95.31"
        },
        ranking_member: {
            message: "@RepAdamSchiff ",
            id: "S001150",
            thomas_id: "1635",
            api_uri: "https://api.propublica.org/congress/v1/members/S001150.json",
            first_name: "Adam",
            middle_name: "B.",
            last_name: "Schiff",
            party: "D",
            twitter_account: "RepAdamSchiff",
            facebook_account: "RepAdamSchiff",
            facebook_id: "9086721830",
            google_entity_id: "/m/024tls",
            url: "http://schiff.house.gov",
            rss_url: "",
            domain: "schiff.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "16",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "20",
            total_present: "0",
            state: "CA",
            district: "28",
            missed_votes_pct: 1.51,
            votes_with_party_pct: "96.78"
        }
    }, {
        committee: {
            id: "HSBG",
            name: "Select Committee on Benghazi",
            url: "http://benghazi.house.gov/",
            democratic_rss: "",
            republican_rss: "",
            api_uri: "https://api.propublica.org/congress/v1/114/house/committees/HSBG.json",
            chair: "Trey Gowdy",
            chair_id: "G000566",
            chair_party: "R",
            chair_state: "SC",
            chair_uri: "https://api.propublica.org/congress/v1/members/G000566.json",
            ranking_member_id: "C000984"
        },
        chair: {
            message: "@TGowdySC ",
            id: "G000566",
            thomas_id: "2058",
            api_uri: "https://api.propublica.org/congress/v1/members/G000566.json",
            first_name: "Trey",
            middle_name: null,
            last_name: "Gowdy",
            party: "R",
            twitter_account: "TGowdySC",
            facebook_account: "143059759084016",
            facebook_id: "143059759084016",
            google_entity_id: "/m/0c3x3rz",
            url: "https://gowdy.house.gov",
            rss_url: "https://gowdy.house.gov/rss.xml",
            domain: "gowdy.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "6",
            next_election: "2016",
            total_votes: "1324",
            missed_votes: "60",
            total_present: "0",
            state: "SC",
            district: "4",
            missed_votes_pct: 4.53,
            votes_with_party_pct: "96.36"
        },
        ranking_member: {
            message: "@RepCummings ",
            id: "C000984",
            thomas_id: "256",
            api_uri: "https://api.propublica.org/congress/v1/members/C000984.json",
            first_name: "Elijah",
            middle_name: "E.",
            last_name: "Cummings",
            party: "D",
            twitter_account: "RepCummings",
            facebook_account: "elijahcummings",
            facebook_id: "291368465380",
            google_entity_id: "/m/025k9h",
            url: "http://cummings.house.gov",
            rss_url: "https://cummings.house.gov/rss.xml",
            domain: "cummings.house.gov",
            dw_nominate: "",
            ideal_point: "",
            seniority: "22",
            next_election: "2016",
            total_votes: "1325",
            missed_votes: "39",
            total_present: "0",
            state: "MD",
            district: "7",
            missed_votes_pct: 2.94,
            votes_with_party_pct: "97.05"
        }
    }]
    return services;
})
