var app = angular.module('app');

app.factory('senateCommittees', function() {
    var services = {};

    services.committees = [{
        "committee": {
            "id": "SSAF",
            "name": "Committee on Agriculture, Nutrition, and Forestry",
            "url": "http://agriculture.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSAF.json",
            "chair": "Pat Roberts",
            "chair_id": "R000307",
            "chair_party": "R",
            "chair_state": "KS",
            "chair_uri": "https://api.propublica.org/congress/v1/members/R000307.json",
            "ranking_member_id": "S000770"
        },
        "chair": {
            "message": "@SenPatRoberts ",
            "id": "R000307",
            "thomas_id": "968",
            "api_uri": "https://api.propublica.org/congress/v1/members/R000307.json",
            "first_name": "Pat",
            "middle_name": null,
            "last_name": "Roberts",
            "party": "R",
            "twitter_account": "SenPatRoberts",
            "facebook_account": "SenPatRoberts",
            "facebook_id": "205694792808927",
            "google_entity_id": "/m/01_pdv",
            "url": "http://www.roberts.senate.gov",
            "rss_url": "http://www.roberts.senate.gov/public/index.cfm?a=RSS.Feed",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "21",
            "next_election": "2020",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "KS",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenPatRoberts "
        },
        "ranking_member": {
            "message": "@SenStabenow",
            "id": "S000770",
            "thomas_id": "1531",
            "api_uri": "https://api.propublica.org/congress/v1/members/S000770.json",
            "first_name": "Debbie",
            "middle_name": null,
            "last_name": "Stabenow",
            "party": "D",
            "twitter_account": "SenStabenow",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/01xh64",
            "url": "http://www.stabenow.senate.gov",
            "rss_url": "",
            "domain": "www.stabenow.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "17",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "MI",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "100.00",
            "message": "@SenStabenow "
        }
    }, {
        "committee": {
            "id": "SSAP",
            "name": "Committee on Appropriations",
            "url": "http://appropriations.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSAP.json",
            "chair": "Thad Cochran",
            "chair_id": "C000567",
            "chair_party": "R",
            "chair_state": "MS",
            "chair_uri": "https://api.propublica.org/congress/v1/members/C000567.json",
            "ranking_member_id": "M000702"
        },
        "chair": {
            "message": "@SenThadCochran ",
            "id": "C000567",
            "thomas_id": "213",
            "api_uri": "https://api.propublica.org/congress/v1/members/C000567.json",
            "first_name": "Thad",
            "middle_name": null,
            "last_name": "Cochran",
            "party": "R",
            "twitter_account": "SenThadCochran",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/01fmcd",
            "url": "http://www.cochran.senate.gov",
            "rss_url": "http://www.cochran.senate.gov/public/index.cfm/rss/taggedfeed?Type=news-releases&amp;region=&amp;issue=",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "39",
            "next_election": "2020",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "MS",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenThadCochran "
        }
    }, {
        "committee": {
            "id": "SSAS",
            "name": "Committee on Armed Services",
            "url": "http://armed-services.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSAS.json",
            "chair": "John McCain",
            "chair_id": "M000303",
            "chair_party": "R",
            "chair_state": "AZ",
            "chair_uri": "https://api.propublica.org/congress/v1/members/M000303.json",
            "ranking_member_id": "R000122"
        },
        "chair": {
            "message": "@SenJohnMcCain ",
            "id": "M000303",
            "thomas_id": "754",
            "api_uri": "https://api.propublica.org/congress/v1/members/M000303.json",
            "first_name": "John",
            "middle_name": null,
            "last_name": "McCain",
            "party": "R",
            "twitter_account": "SenJohnMcCain",
            "facebook_account": "johnmccain",
            "facebook_id": "6425923706",
            "google_entity_id": "/m/0bymv",
            "url": "http://www.mccain.senate.gov",
            "rss_url": "http://www.mccain.senate.gov/public/?a=rss.feed",
            "domain": "www.mccain.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "31",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "AZ",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenJohnMcCain "
        },
        "ranking_member": {
            "message": "@SenJackReed",
            "id": "R000122",
            "thomas_id": "949",
            "api_uri": "https://api.propublica.org/congress/v1/members/R000122.json",
            "first_name": "Jack",
            "middle_name": null,
            "last_name": "Reed",
            "party": "D",
            "twitter_account": "SenJackReed",
            "facebook_account": "SenJackReed",
            "facebook_id": "213866375370646",
            "google_entity_id": "/m/0202mc",
            "url": "https://www.reed.senate.gov",
            "rss_url": "https://www.reed.senate.gov/rss/feeds/?type=press",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "21",
            "next_election": "2020",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "RI",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenJackReed "
        }
    }, {
        "committee": {
            "id": "SSBK",
            "name": "Committee on Banking, Housing, and Urban Affairs",
            "url": "http://banking.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSBK.json",
            "chair": "Michael D. Crapo",
            "chair_id": "C000880",
            "chair_party": "R",
            "chair_state": "ID",
            "chair_uri": "https://api.propublica.org/congress/v1/members/C000880.json",
            "ranking_member_id": "B000944"
        },
        "chair": {
            "message": "@MikeCrapo ",
            "id": "C000880",
            "thomas_id": "250",
            "api_uri": "https://api.propublica.org/congress/v1/members/C000880.json",
            "first_name": "Michael",
            "middle_name": "D.",
            "last_name": "Crapo",
            "party": "R",
            "twitter_account": "MikeCrapo",
            "facebook_account": "mikecrapo",
            "facebook_id": "80335332266",
            "google_entity_id": "/m/021pgp",
            "url": "http://www.crapo.senate.gov",
            "rss_url": "",
            "domain": "crapo.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "19",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "ID",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@MikeCrapo "
        },
        "ranking_member": {
            "message": "@SenSherrodBrown",
            "id": "B000944",
            "thomas_id": "136",
            "api_uri": "https://api.propublica.org/congress/v1/members/B000944.json",
            "first_name": "Sherrod",
            "middle_name": "",
            "last_name": "Brown",
            "party": "D",
            "twitter_account": "SenSherrodBrown",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/034s80",
            "url": "https://www.brown.senate.gov",
            "rss_url": "http://www.brown.senate.gov/rss/feeds/?type=all&amp;",
            "domain": "www.brown.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "5",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "OH",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "100.00",
            "message": "@SenSherrodBrown "
        }
    }, {
        "committee": {
            "id": "SSCM",
            "name": "Committee on Commerce, Science, and Transportation",
            "url": "http://commerce.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSCM.json",
            "chair": "John Thune",
            "chair_id": "T000250",
            "chair_party": "R",
            "chair_state": "SD",
            "chair_uri": "https://api.propublica.org/congress/v1/members/T000250.json",
            "ranking_member_id": "N000032"
        },
        "chair": {
            "message": "@SenJohnThune ",
            "id": "T000250",
            "thomas_id": "1534",
            "api_uri": "https://api.propublica.org/congress/v1/members/T000250.json",
            "first_name": "John",
            "middle_name": null,
            "last_name": "Thune",
            "party": "R",
            "twitter_account": "SenJohnThune",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/03ybyn",
            "url": "http://www.thune.senate.gov",
            "rss_url": "http://www.thune.senate.gov/public/?a=RSS.Feed",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "13",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "SD",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenJohnThune "
        },
        "ranking_member": {
            "message": "@SenBillNelson",
            "id": "N000032",
            "thomas_id": "859",
            "api_uri": "https://api.propublica.org/congress/v1/members/N000032.json",
            "first_name": "Bill",
            "middle_name": null,
            "last_name": "Nelson",
            "party": "D",
            "twitter_account": "SenBillNelson",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/01_pb_",
            "url": "https://www.billnelson.senate.gov",
            "rss_url": "",
            "domain": "billnelson.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "17",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "FL",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "100.00",
            "message": "@SenBillNelson "
        }
    }, {
        "committee": {
            "id": "SSEG",
            "name": "Committee on Energy and Natural Resources",
            "url": "http://energy.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSEG.json",
            "chair": "Lisa Murkowski",
            "chair_id": "M001153",
            "chair_party": "R",
            "chair_state": "AK",
            "chair_uri": "https://api.propublica.org/congress/v1/members/M001153.json",
            "ranking_member_id": "C000127"
        },
        "chair": {
            "message": "@LisaMurkowski ",
            "id": "M001153",
            "thomas_id": "1694",
            "api_uri": "https://api.propublica.org/congress/v1/members/M001153.json",
            "first_name": "Lisa",
            "middle_name": null,
            "last_name": "Murkowski",
            "party": "R",
            "twitter_account": "LisaMurkowski",
            "facebook_account": "SenLisaMurkowski",
            "facebook_id": "25271170290",
            "google_entity_id": "/m/0202kt",
            "url": "https://www.murkowski.senate.gov",
            "rss_url": "",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "17",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "AK",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@LisaMurkowski "
        },
        "ranking_member": {
            "message": "@SenatorCantwell",
            "id": "C000127",
            "thomas_id": "172",
            "api_uri": "https://api.propublica.org/congress/v1/members/C000127.json",
            "first_name": "Maria",
            "middle_name": null,
            "last_name": "Cantwell",
            "party": "D",
            "twitter_account": "SenatorCantwell",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/01x68t",
            "url": "https://www.cantwell.senate.gov",
            "rss_url": "",
            "domain": "www.cantwell.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "17",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "WA",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenatorCantwell "
        }
    }, {
        "committee": {
            "id": "SSEV",
            "name": "Committee on Environment and Public Works",
            "url": "http://www.epw.senate.gov/public/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSEV.json",
            "chair": "John Barrasso",
            "chair_id": "B001261",
            "chair_party": "R",
            "chair_state": "WY",
            "chair_uri": "https://api.propublica.org/congress/v1/members/B001261.json",
            "ranking_member_id": "B000711"
        },
        "chair": {
            "message": "@SenJohnBarrasso ",
            "id": "B001261",
            "thomas_id": "1881",
            "api_uri": "https://api.propublica.org/congress/v1/members/B001261.json",
            "first_name": "John",
            "middle_name": null,
            "last_name": "Barrasso",
            "party": "R",
            "twitter_account": "SenJohnBarrasso",
            "facebook_account": "johnbarrasso",
            "facebook_id": "21146775942",
            "google_entity_id": "/m/02rsm32",
            "url": "http://www.barrasso.senate.gov",
            "rss_url": "",
            "domain": "www.barrasso.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "11",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "WY",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenJohnBarrasso "
        }
    }, {
        "committee": {
            "id": "SSFI",
            "name": "Committee on Finance",
            "url": "http://www.finance.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSFI.json",
            "chair": "Orrin G. Hatch",
            "chair_id": "H000338",
            "chair_party": "R",
            "chair_state": "UT",
            "chair_uri": "https://api.propublica.org/congress/v1/members/H000338.json",
            "ranking_member_id": "W000779"
        },
        "chair": {
            "message": "@SenOrrinHatch ",
            "id": "H000338",
            "thomas_id": "1351",
            "api_uri": "https://api.propublica.org/congress/v1/members/H000338.json",
            "first_name": "Orrin",
            "middle_name": "G.",
            "last_name": "Hatch",
            "party": "R",
            "twitter_account": "SenOrrinHatch",
            "facebook_account": "senatororrinhatch",
            "facebook_id": "",
            "google_entity_id": "/m/016mj4",
            "url": "http://www.hatch.senate.gov",
            "rss_url": "http://www.hatch.senate.gov/public/index.cfm/rss/feed",
            "domain": "www.hatch.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "41",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "UT",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "93.94",
            "message": "@SenOrrinHatch "
        },
        "ranking_member": {
            "message": "@RonWyden",
            "id": "W000779",
            "thomas_id": "1247",
            "api_uri": "https://api.propublica.org/congress/v1/members/W000779.json",
            "first_name": "Ron",
            "middle_name": null,
            "last_name": "Wyden",
            "party": "D",
            "twitter_account": "RonWyden",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/0178p9",
            "url": "https://www.wyden.senate.gov",
            "rss_url": "",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "22",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "OR",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "90.91",
            "message": "@RonWyden "
        }
    }, {
        "committee": {
            "id": "SSFR",
            "name": "Committee on Foreign Relations",
            "url": "http://www.foreign.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSFR.json",
            "chair": "Bob Corker",
            "chair_id": "C001071",
            "chair_party": "R",
            "chair_state": "TN",
            "chair_uri": "https://api.propublica.org/congress/v1/members/C001071.json",
            "ranking_member_id": "C000141"
        },
        "chair": {
            "message": "@SenBobCorker ",
            "id": "C001071",
            "thomas_id": "1825",
            "api_uri": "https://api.propublica.org/congress/v1/members/C001071.json",
            "first_name": "Bob",
            "middle_name": null,
            "last_name": "Corker",
            "party": "R",
            "twitter_account": "SenBobCorker",
            "facebook_account": "bobcorker",
            "facebook_id": "109251415789533",
            "google_entity_id": "/m/0d9fz3",
            "url": "http://www.corker.senate.gov",
            "rss_url": "http://www.corker.senate.gov/public/index.cfm/rss/feed",
            "domain": "www.corker.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "11",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "TN",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "100.00",
            "message": "@SenBobCorker "
        },
        "ranking_member": {
            "message": "@SenatorCardin",
            "id": "C000141",
            "thomas_id": "174",
            "api_uri": "https://api.propublica.org/congress/v1/members/C000141.json",
            "first_name": "Benjamin",
            "middle_name": "L.",
            "last_name": "Cardin",
            "party": "D",
            "twitter_account": "SenatorCardin",
            "facebook_account": "senatorbencardin",
            "facebook_id": "120421834675191",
            "google_entity_id": "/m/025k3k",
            "url": "https://www.cardin.senate.gov",
            "rss_url": "",
            "domain": "www.cardin.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "11",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "MD",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "100.00",
            "message": "@SenatorCardin "
        }
    }, {
        "committee": {
            "id": "SSHR",
            "name": "Committee on Health, Education, Labor, and Pensions",
            "url": "http://www.help.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSHR.json",
            "chair": "Lamar  Alexander",
            "chair_id": "A000360",
            "chair_party": "R",
            "chair_state": "TN",
            "chair_uri": "https://api.propublica.org/congress/v1/members/A000360.json",
            "ranking_member_id": "M001111"
        },
        "chair": {
            "message": "@SenAlexander ",
            "id": "A000360",
            "thomas_id": "1695",
            "api_uri": "https://api.propublica.org/congress/v1/members/A000360.json",
            "first_name": "Lamar",
            "middle_name": "",
            "last_name": "Alexander",
            "party": "R",
            "twitter_account": "SenAlexander",
            "facebook_account": "senatorlamaralexander",
            "facebook_id": "89927603836",
            "google_entity_id": "/m/01rbs3",
            "url": "https://www.alexander.senate.gov/public/index.cfm/home",
            "rss_url": "http://www.alexander.senate.gov/public/?a=RSS.Feed",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "15",
            "next_election": "2020",
            "total_votes": "33",
            "missed_votes": "1",
            "total_present": "0",
            "state": "TN",
            "missed_votes_pct": "3.03",
            "votes_with_party_pct": "96.88",
            "message": "@SenAlexander "
        },
        "ranking_member": {
            "message": "@PattyMurray",
            "id": "M001111",
            "thomas_id": "1409",
            "api_uri": "https://api.propublica.org/congress/v1/members/M001111.json",
            "first_name": "Patty",
            "middle_name": null,
            "last_name": "Murray",
            "party": "D",
            "twitter_account": "PattyMurray",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/018qx5",
            "url": "http://www.murray.senate.gov/public",
            "rss_url": "http://www.murray.senate.gov/public/?a=RSS.Feed",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "25",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "WA",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "93.94",
            "message": "@PattyMurray "
        }
    }, {
        "committee": {
            "id": "SSGA",
            "name": "Committee on Homeland Security and Governmental Affairs",
            "url": "https://www.hsgac.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSGA.json",
            "chair": "Ron Johnson",
            "chair_id": "J000293",
            "chair_party": "R",
            "chair_state": "WI",
            "chair_uri": "https://api.propublica.org/congress/v1/members/J000293.json",
            "ranking_member_id": "C000174"
        },
        "chair": {
            "message": "@SenRonJohnson ",
            "id": "J000293",
            "thomas_id": "2086",
            "api_uri": "https://api.propublica.org/congress/v1/members/J000293.json",
            "first_name": "Ron",
            "middle_name": null,
            "last_name": "Johnson",
            "party": "R",
            "twitter_account": "SenRonJohnson",
            "facebook_account": "senronjohnson",
            "facebook_id": "186181661410703",
            "google_entity_id": "/m/0cmdpzc",
            "url": "http://www.ronjohnson.senate.gov",
            "rss_url": "",
            "domain": "www.ronjohnson.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "7",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "WI",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "100.00",
            "message": "@SenRonJohnson "
        },
        "ranking_member": {
            "message": "@SenatorCarper",
            "id": "C000174",
            "thomas_id": "179",
            "api_uri": "https://api.propublica.org/congress/v1/members/C000174.json",
            "first_name": "Thomas",
            "middle_name": "R.",
            "last_name": "Carper",
            "party": "D",
            "twitter_account": "SenatorCarper",
            "facebook_account": "tomcarper",
            "facebook_id": "124891107521733",
            "google_entity_id": "/m/01xw7t",
            "url": "http://www.carper.senate.gov/public",
            "rss_url": "http://www.carper.senate.gov/public/index.cfm/rss/feed",
            "domain": "www.carper.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "17",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "1",
            "total_present": "0",
            "state": "DE",
            "missed_votes_pct": "3.03",
            "votes_with_party_pct": "96.88",
            "message": "@SenatorCarper "
        }
    }, {
        "committee": {
            "id": "SLIA",
            "name": "Committee on Indian Affairs",
            "url": "http://www.indian.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SLIA.json",
            "chair": "John Hoeven",
            "chair_id": "H001061",
            "chair_party": "R",
            "chair_state": "ND",
            "chair_uri": "https://api.propublica.org/congress/v1/members/H001061.json",
            "ranking_member_id": "B001261"
        },
        "chair": {
            "message": "@SenJohnHoeven ",
            "id": "H001061",
            "thomas_id": "2079",
            "api_uri": "https://api.propublica.org/congress/v1/members/H001061.json",
            "first_name": "John",
            "middle_name": null,
            "last_name": "Hoeven",
            "party": "R",
            "twitter_account": "SenJohnHoeven",
            "facebook_account": "SenatorJohnHoeven",
            "facebook_id": "194483057244478",
            "google_entity_id": "/m/01qb45",
            "url": "https://www.hoeven.senate.gov",
            "rss_url": "",
            "domain": "www.hoeven.senate.gov/public/",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "7",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "ND",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "100.00",
            "message": "@SenJohnHoeven "
        },
        "ranking_member": {
            "message": "@SenJohnBarrasso",
            "id": "B001261",
            "thomas_id": "1881",
            "api_uri": "https://api.propublica.org/congress/v1/members/B001261.json",
            "first_name": "John",
            "middle_name": null,
            "last_name": "Barrasso",
            "party": "R",
            "twitter_account": "SenJohnBarrasso",
            "facebook_account": "johnbarrasso",
            "facebook_id": "21146775942",
            "google_entity_id": "/m/02rsm32",
            "url": "http://www.barrasso.senate.gov",
            "rss_url": "",
            "domain": "www.barrasso.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "11",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "WY",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenJohnBarrasso "
        }
    }, {
        "committee": {
            "id": "SSRA",
            "name": "Committee on Rules and Administration",
            "url": "http://www.rules.senate.gov/public/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSRA.json",
            "chair": "Richard C. Shelby",
            "chair_id": "S000320",
            "chair_party": "R",
            "chair_state": "AL",
            "chair_uri": "https://api.propublica.org/congress/v1/members/S000320.json",
            "ranking_member_id": "S000148"
        },
        "chair": {
            "message": "@SenShelby ",
            "id": "S000320",
            "thomas_id": "1049",
            "api_uri": "https://api.propublica.org/congress/v1/members/S000320.json",
            "first_name": "Richard",
            "middle_name": "C.",
            "last_name": "Shelby",
            "party": "R",
            "twitter_account": "SenShelby",
            "facebook_account": "RichardShelby",
            "facebook_id": "50850514797",
            "google_entity_id": "/m/020yj1",
            "url": "http://www.shelby.senate.gov",
            "rss_url": "",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "31",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "AL",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenShelby "
        },
        "ranking_member": {
            "message": "@SenSchumer",
            "id": "S000148",
            "thomas_id": "1036",
            "api_uri": "https://api.propublica.org/congress/v1/members/S000148.json",
            "first_name": "Charles",
            "middle_name": "E.",
            "last_name": "Schumer",
            "party": "D",
            "twitter_account": "SenSchumer",
            "facebook_account": "chuckschumer",
            "facebook_id": "15771239406",
            "google_entity_id": "/m/01w74d",
            "url": "https://www.schumer.senate.gov",
            "rss_url": "",
            "domain": "www.schumer.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "19",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "NY",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenSchumer "
        }
    }, {
        "committee": {
            "id": "SSSB",
            "name": "Committee on Small Business and Entrepreneurship",
            "url": "http://www.sbc.senate.gov/public/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSSB.json",
            "chair": "Jim Risch",
            "chair_id": "R000584",
            "chair_party": "R",
            "chair_state": "ID",
            "chair_uri": "https://api.propublica.org/congress/v1/members/R000584.json",
            "ranking_member_id": "S001181"
        },
        "chair": {
            "message": "@SenatorRisch ",
            "id": "R000584",
            "thomas_id": "1896",
            "api_uri": "https://api.propublica.org/congress/v1/members/R000584.json",
            "first_name": "Jim",
            "middle_name": null,
            "last_name": "Risch",
            "party": "R",
            "twitter_account": "SenatorRisch",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/06y9p0",
            "url": "http://www.risch.senate.gov",
            "rss_url": "",
            "domain": "www.risch.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "9",
            "next_election": "2020",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "ID",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenatorRisch "
        },
        "ranking_member": {
            "message": "@SenatorShaheen",
            "id": "S001181",
            "thomas_id": "1901",
            "api_uri": "https://api.propublica.org/congress/v1/members/S001181.json",
            "first_name": "Jeanne",
            "middle_name": null,
            "last_name": "Shaheen",
            "party": "D",
            "twitter_account": "SenatorShaheen",
            "facebook_account": "SenatorShaheen",
            "facebook_id": "127503767282103",
            "google_entity_id": "/m/01rrm2",
            "url": "https://www.shaheen.senate.gov",
            "rss_url": "",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "9",
            "next_election": "2020",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "NH",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenatorShaheen "
        }
    }, {
        "committee": {
            "id": "SSBU",
            "name": "Committee on the Budget",
            "url": "http://www.budget.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSBU.json",
            "chair": "Michael B. Enzi",
            "chair_id": "E000285",
            "chair_party": "R",
            "chair_state": "WY",
            "chair_uri": "https://api.propublica.org/congress/v1/members/E000285.json",
            "ranking_member_id": "S000033"
        },
        "chair": {
            "message": "@SenatorEnzi ",
            "id": "E000285",
            "thomas_id": "1542",
            "api_uri": "https://api.propublica.org/congress/v1/members/E000285.json",
            "first_name": "Michael",
            "middle_name": "B.",
            "last_name": "Enzi",
            "party": "R",
            "twitter_account": "SenatorEnzi",
            "facebook_account": "mikeenzi",
            "facebook_id": "23068049436",
            "google_entity_id": "/m/021ph1",
            "url": "http://www.enzi.senate.gov",
            "rss_url": "http://www.enzi.senate.gov/public/index.cfm/rss/feed",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "21",
            "next_election": "2020",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "WY",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenatorEnzi "
        },
        "ranking_member": {
            "message": "@SenSanders",
            "id": "S000033",
            "thomas_id": "1010",
            "api_uri": "https://api.propublica.org/congress/v1/members/S000033.json",
            "first_name": "Bernard",
            "middle_name": null,
            "last_name": "Sanders",
            "party": "I",
            "twitter_account": "SenSanders",
            "facebook_account": "senatorsanders",
            "facebook_id": "9124187907",
            "google_entity_id": "/m/01_gbv",
            "url": "http://www.sanders.senate.gov",
            "rss_url": "http://www.sanders.senate.gov/rss/feeds/?press",
            "domain": "www.sanders.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "11",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "VT",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "90.91",
            "message": "@SenSanders "
        }
    }, {
        "committee": {
            "id": "SSJU",
            "name": "Committee on the Judiciary",
            "url": "https://www.judiciary.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSJU.json",
            "chair": "Charles E. Grassley",
            "chair_id": "G000386",
            "chair_party": "R",
            "chair_state": "IA",
            "chair_uri": "https://api.propublica.org/congress/v1/members/G000386.json",
            "ranking_member_id": "L000174"
        },
        "chair": {
            "message": "@ChuckGrassley ",
            "id": "G000386",
            "thomas_id": "457",
            "api_uri": "https://api.propublica.org/congress/v1/members/G000386.json",
            "first_name": "Charles",
            "middle_name": "E.",
            "last_name": "Grassley",
            "party": "R",
            "twitter_account": "ChuckGrassley",
            "facebook_account": "grassley",
            "facebook_id": "106480645796",
            "google_entity_id": "/m/020ymy",
            "url": "http://www.grassley.senate.gov",
            "rss_url": "http://www.grassley.senate.gov/?q=rss.xml",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "37",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "IA",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "90.91",
            "message": "@ChuckGrassley "
        },
        "ranking_member": {
            "message": "@SenatorLeahy",
            "id": "L000174",
            "thomas_id": "1383",
            "api_uri": "https://api.propublica.org/congress/v1/members/L000174.json",
            "first_name": "Patrick",
            "middle_name": "J.",
            "last_name": "Leahy",
            "party": "D",
            "twitter_account": "SenatorLeahy",
            "facebook_account": "SenatorPatrickLeahy",
            "facebook_id": "178569152181267",
            "google_entity_id": "/m/0202kf",
            "url": "https://www.leahy.senate.gov",
            "rss_url": "",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "43",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "VT",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@SenatorLeahy "
        }
    }, {
        "committee": {
            "id": "SSVA",
            "name": "Committee on Veterans&#39; Affairs",
            "url": "http://www.veterans.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSVA.json",
            "chair": "Johnny Isakson",
            "chair_id": "I000055",
            "chair_party": "R",
            "chair_state": "GA",
            "chair_uri": "https://api.propublica.org/congress/v1/members/I000055.json",
            "ranking_member_id": "B001277"
        },
        "chair": {
            "message": "@SenatorIsakson ",
            "id": "I000055",
            "thomas_id": "1608",
            "api_uri": "https://api.propublica.org/congress/v1/members/I000055.json",
            "first_name": "Johnny",
            "middle_name": null,
            "last_name": "Isakson",
            "party": "R",
            "twitter_account": "SenatorIsakson",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/02556q",
            "url": "http://www.isakson.senate.gov",
            "rss_url": "http://www.isakson.senate.gov/public/?a=RSS.Feed",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "13",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "1",
            "total_present": "0",
            "state": "GA",
            "missed_votes_pct": "3.03",
            "votes_with_party_pct": "96.88",
            "message": "@SenatorIsakson "
        },
        "ranking_member": {
            "message": "@SenBlumenthal",
            "id": "B001277",
            "thomas_id": "2076",
            "api_uri": "https://api.propublica.org/congress/v1/members/B001277.json",
            "first_name": "Richard",
            "middle_name": null,
            "last_name": "Blumenthal",
            "party": "D",
            "twitter_account": "SenBlumenthal",
            "facebook_account": "SenBlumenthal",
            "facebook_id": "289987304364966",
            "google_entity_id": "/m/03tg8m",
            "url": "https://www.blumenthal.senate.gov",
            "rss_url": "http://www.blumenthal.senate.gov/rss/feeds/?type=press",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "7",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "1",
            "total_present": "0",
            "state": "CT",
            "missed_votes_pct": "3.03",
            "votes_with_party_pct": "90.63",
            "message": "@SenBlumenthal "
        }
    }, {
        "committee": {
            "id": "SLET",
            "name": "Select Committee on Ethics",
            "url": "http://www.ethics.senate.gov/public/",
            "democratic_rss": "",
            "republican_rss": "http://www.ethics.senate.gov/public/?a=RSS.Feed",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SLET.json",
            "chair": "Johnny Isakson",
            "chair_id": "I000055",
            "chair_party": "R",
            "chair_state": "GA",
            "chair_uri": "https://api.propublica.org/congress/v1/members/I000055.json",
            "ranking_member_id": "I000055"
        },
        "chair": {
            "message": "@SenatorIsakson ",
            "id": "I000055",
            "thomas_id": "1608",
            "api_uri": "https://api.propublica.org/congress/v1/members/I000055.json",
            "first_name": "Johnny",
            "middle_name": null,
            "last_name": "Isakson",
            "party": "R",
            "twitter_account": "SenatorIsakson",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/02556q",
            "url": "http://www.isakson.senate.gov",
            "rss_url": "http://www.isakson.senate.gov/public/?a=RSS.Feed",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "13",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "1",
            "total_present": "0",
            "state": "GA",
            "missed_votes_pct": "3.03",
            "votes_with_party_pct": "96.88",
            "message": "@SenatorIsakson "
        },
        "ranking_member": {
            "message": "@SenatorIsakson",
            "id": "I000055",
            "thomas_id": "1608",
            "api_uri": "https://api.propublica.org/congress/v1/members/I000055.json",
            "first_name": "Johnny",
            "middle_name": null,
            "last_name": "Isakson",
            "party": "R",
            "twitter_account": "SenatorIsakson",
            "facebook_account": "",
            "facebook_id": "",
            "google_entity_id": "/m/02556q",
            "url": "http://www.isakson.senate.gov",
            "rss_url": "http://www.isakson.senate.gov/public/?a=RSS.Feed",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "13",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "1",
            "total_present": "0",
            "state": "GA",
            "missed_votes_pct": "3.03",
            "votes_with_party_pct": "96.88",
            "message": "@SenatorIsakson "
        }
    }, {
        "committee": {
            "id": "SLIN",
            "name": "Select Committee on Intelligence",
            "url": "http://www.intelligence.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SLIN.json",
            "chair": "Richard M. Burr",
            "chair_id": "B001135",
            "chair_party": "R",
            "chair_state": "NC",
            "chair_uri": "https://api.propublica.org/congress/v1/members/B001135.json",
            "ranking_member_id": "C000286"
        },
        "chair": {
            "message": "@SenatorBurr ",
            "id": "B001135",
            "thomas_id": "153",
            "api_uri": "https://api.propublica.org/congress/v1/members/B001135.json",
            "first_name": "Richard",
            "middle_name": "M.",
            "last_name": "Burr",
            "party": "R",
            "twitter_account": "SenatorBurr",
            "facebook_account": "SenatorRichardBurr",
            "facebook_id": "132653626787856",
            "google_entity_id": "/m/03g_s9",
            "url": "http://www.burr.senate.gov",
            "rss_url": "",
            "domain": "burr.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "13",
            "next_election": "2022",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "NC",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "100.00",
            "message": "@SenatorBurr "
        }
    }, {
        "committee": {
            "id": "SPAG",
            "name": "Special Committee on Aging",
            "url": "http://www.aging.senate.gov/",
            "democratic_rss": "",
            "republican_rss": "",
            "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SPAG.json",
            "chair": "Susan Collins",
            "chair_id": "C001035",
            "chair_party": "R",
            "chair_state": "ME",
            "chair_uri": "https://api.propublica.org/congress/v1/members/C001035.json",
            "ranking_member_id": "M001170"
        },
        "chair": {
            "message": "@SenatorCollins ",
            "id": "C001035",
            "thomas_id": "1541",
            "api_uri": "https://api.propublica.org/congress/v1/members/C001035.json",
            "first_name": "Susan",
            "middle_name": null,
            "last_name": "Collins",
            "party": "R",
            "twitter_account": "SenatorCollins",
            "facebook_account": "susancollins",
            "facebook_id": "7593313361",
            "google_entity_id": "/m/020y8m",
            "url": "https://www.collins.senate.gov",
            "rss_url": "https://www.collins.senate.gov/?q=rss.xml",
            "domain": "",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "21",
            "next_election": "2020",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "ME",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "72.73",
            "message": "@SenatorCollins "
        },
        "ranking_member": {
            "message": "@McCaskillOffice",
            "id": "M001170",
            "thomas_id": "1820",
            "api_uri": "https://api.propublica.org/congress/v1/members/M001170.json",
            "first_name": "Claire",
            "middle_name": null,
            "last_name": "McCaskill",
            "party": "D",
            "twitter_account": "McCaskillOffice",
            "facebook_account": "senatormccaskill",
            "facebook_id": "131498087618",
            "google_entity_id": "/m/040_w4",
            "url": "https://www.mccaskill.senate.gov",
            "rss_url": "http://www.mccaskill.senate.gov/rss/feeds/?press",
            "domain": "www.mccaskill.senate.gov",
            "dw_nominate": "",
            "ideal_point": "",
            "seniority": "11",
            "next_election": "2018",
            "total_votes": "33",
            "missed_votes": "0",
            "total_present": "0",
            "state": "MO",
            "missed_votes_pct": "0.00",
            "votes_with_party_pct": "96.97",
            "message": "@McCaskillOffice "
        }
    }]
    return services;
})
